# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Ankit Gupta's Blog

author:
  name:           'Ankit Gupta'

permalink: /blog/:year/:title:output_ext

disqus:
  shortname: ankitgupta

google_analytics: G-G7BDENNS2B
