# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Ankit Gupta's Blog

author:
  name:           'Ankit Gupta'

disqus:
  shortname: ankitgupta

google_analytics: UA-29493248-1

excerpt_separator: "<!--more-->"

twitter_username: AnkitGupta_89
linkedin_username: ankit2801
github_username: gupta-ankit

