# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Ankit Gupta
description:      Visual Analytics Researcher and Web Developer

author:
  name:           'Ankit Gupta'
  url:            https://twitter.com/AnkitGupta_89

paginate:         5

sidebar_home_link:  false

#custom vars
version:            3.4.1
github:
  repo:             https://github.com/fongandrew/hydeout


disqus:
  shortname: ankitgupta

google_analytics: UA-29493248-1


defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      author: "Ankit Gupta"
      comments: true
        
