# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Ankit Gupta
description:      HCI Researcher | HIT Researcher | Full Stack Developer

author:
  name:           'Ankit Gupta'

paginate:         5
paginate_path: "/blog/page:num"

#custom vars
version:            3.4.1

disqus:
  shortname: ankitgupta

google_analytics: UA-29493248-1


twitter_username: AnkitGupta_89
linkedin_username: ankit2801
github_username: gupta-ankit

defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      author: "Ankit Gupta"
      comments: true
